### PR TITLE
copyediting

### PR DESCRIPTION
**Pull request by ha0ye**
some spelling and grammar fixes
make persona pronouns gender-neutral

### CODE REVIEW

**Comment by ethanwhite** [comment]
Question on the persona pronouns changes. The pronouns (and names) were intentionally selected to represent a diverse group of folks. In the pronouns case it was one use of he/him, one use of she/her, and one use of they/them. Is you're take that it is better to use they/them exclusively in this sort of context?

**Comment by ha0ye** [comment]
Since there are pronouns beyond the he/she/they set, I prefer using "they" in the sense of unknown pronouns, so as to not give the impression of communicating "these are the pronouns".

Also I did notice that the professor was the persona using he/him, so felt that could be avoided too.

Not going to be a big deal regardless of choices.

**Comment by ethanwhite** [comment]
I'm happy to make the change, just trying to understand the general best practice in cases like this. A lot of the stuff I've read in the general focuses more on maximizing representation where as this approach avoids any exclusion. I can see both approaches making sense. If we're going the avoid exclusion approach then it would see consistent to also get rid of names (since we can't represent all countries and cultures) and just phrase things based on generic descriptions. So if you think this is the best approach go ahead and remove the names as well and make both changes in `paper.md` as well as on the Audience page.

**Comment by ha0ye** [comment]
I don't know that there is a best practice in cases like this. To my mind, personas aren't really the place for representation in the first place. My personal approach around pronouns is to try to be correct and otherwise avoid making assumptions. I think the specific names are useful for describing personas, but the assignment of pronouns is probably not needed. The change is more of a personal preference from me than a standard practice, and you are welcome to revert.

I've also looked into using https://www.behindthename.com/random/ to broaden inclusion from different ethnicities, and then it has felt forced to have names that read as atypical for my mostly-US audience. I've also considered "A", "B", "C" as placeholder names and that has been awkward too.

Maybe I'll try pokemon next.

**Comment by ethanwhite** [comment]
OK. Thanks. If this is how you like it that’s good enough for me. If you can update the PR to include the same changes in paper.md I’ll get it merged. EthanOn Aug 12, 2023, at 2:18 PM, Hao Ye ***@***.***> wrote:﻿
I don't know that there is a best practice in cases like this. To my mind, personas aren't really the place for representation in the first place. My personal approach around pronouns is to try to be correct and otherwise avoid making assumptions. I think the specific names are useful for describing personas, but the assignment of pronouns is probably not needed. The change is more of a personal preference from me than a standard practice, and you are welcome to revert.
I've also looked into using https://www.behindthename.com/random/ to broaden inclusion from different ethnicities, and then it has felt forced to have names that read as atypical for my mostly-US audience. I've also considered "A", "B", "C" as placeholder names and that has been awkward too.
Maybe I'll try pokemon next.

**Comment by ethanwhite** [comment]
Thanks @ha0ye!

**Pull request merged**
